//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileMetadataAssociationManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileMetadataAssociationManager.Resources.LocalizedMessages", typeof(LocalizedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add handler - our property handler is not registered.
        /// </summary>
        internal static string CannotAddHandler {
            get {
                return ResourceManager.GetString("CannotAddHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete &apos;{0}&apos; as it is in use by at least one handler.
        /// </summary>
        internal static string CannotDeleteProfile {
            get {
                return ResourceManager.GetString("CannotDeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing Profiles.
        /// </summary>
        internal static string ChangingProfilesHeader {
            get {
                return ResourceManager.GetString("ChangingProfilesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These changes will be applied to the following extensions: {0}. Do you want to proceed?.
        /// </summary>
        internal static string ChangingProfilesQuestion {
            get {
                return ResourceManager.GetString("ChangingProfilesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing with changes.
        /// </summary>
        internal static string ClosingWithChanges {
            get {
                return ResourceManager.GetString("ClosingWithChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorHeader {
            get {
                return ResourceManager.GetString("ErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some errors occurred during handler setup.
        /// </summary>
        internal static string HandlerSetupIssues {
            get {
                return ResourceManager.GetString("HandlerSetupIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpHeader {
            get {
                return ResourceManager.GetString("HelpHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Profile.
        /// </summary>
        internal static string NewProfileName {
            get {
                return ResourceManager.GetString("NewProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No context menus - our context handler is not registered.
        /// </summary>
        internal static string NoContextMenus {
            get {
                return ResourceManager.GetString("NoContextMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator does not have write permission for &apos;{0}&apos; registry key.
        /// </summary>
        internal static string NoRegistryPermission {
            get {
                return ResourceManager.GetString("NoRegistryPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A profile called &apos;{0}&apos; already exists.
        /// </summary>
        internal static string ProfileAlreadyExists {
            get {
                return ResourceManager.GetString("ProfileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built in.
        /// </summary>
        internal static string ProfileBuiltIn {
            get {
                return ResourceManager.GetString("ProfileBuiltIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string ProfileCustom {
            get {
                return ResourceManager.GetString("ProfileCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not configure Profile.
        /// </summary>
        internal static string ProfileError {
            get {
                return ResourceManager.GetString("ProfileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current property handler for {0} is {1}.
        /// </summary>
        internal static string PropertyHandlerCurrent {
            get {
                return ResourceManager.GetString("PropertyHandlerCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string PropertyHandlerNone {
            get {
                return ResourceManager.GetString("PropertyHandlerNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        internal static string PropertyKeyFormatString {
            get {
                return ResourceManager.GetString("PropertyKeyFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize PropVariant..
        /// </summary>
        internal static string PropVariantInitializationError {
            get {
                return ResourceManager.GetString("PropVariantInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-dimensional SafeArrays not supported..
        /// </summary>
        internal static string PropVariantMultiDimArray {
            get {
                return ResourceManager.GetString("PropVariantMultiDimArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String argument cannot be null or empty..
        /// </summary>
        internal static string PropVariantNullString {
            get {
                return ResourceManager.GetString("PropVariantNullString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Value type is not supported..
        /// </summary>
        internal static string PropVariantTypeNotSupported {
            get {
                return ResourceManager.GetString("PropVariantTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be cast to unsupported type..
        /// </summary>
        internal static string PropVariantUnsupportedType {
            get {
                return ResourceManager.GetString("PropVariantUnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Property Group.
        /// </summary>
        internal static string RemovePropertyGroupHeader {
            get {
                return ResourceManager.GetString("RemovePropertyGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove {0} and its contents from Full details and Preview Panel?.
        /// </summary>
        internal static string RemovePropertyGroupQuestion {
            get {
                return ResourceManager.GetString("RemovePropertyGroupQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Property.
        /// </summary>
        internal static string RemovePropertyHeader {
            get {
                return ResourceManager.GetString("RemovePropertyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove {0} from Full details and Preview Panel?.
        /// </summary>
        internal static string RemovePropertyQuestion {
            get {
                return ResourceManager.GetString("RemovePropertyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have made changes that may require Explorer to be restarted to become effective. Do you want to restart Explorer now?.
        /// </summary>
        internal static string RestartExplorerNow {
            get {
                return ResourceManager.GetString("RestartExplorerNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use drag and drop to populate Full details and Preview Panel, and reorder their contents.
        /// </summary>
        internal static string UseDragDrop {
            get {
                return ResourceManager.GetString("UseDragDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error &quot;{0}&quot; parsing XML store of saved custom profiles.
        /// </summary>
        internal static string XmlParseError {
            get {
                return ResourceManager.GetString("XmlParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error &quot;{0}&quot; updating XML store of saved custom profiles.
        /// </summary>
        internal static string XmlWriteError {
            get {
                return ResourceManager.GetString("XmlWriteError", resourceCulture);
            }
        }
    }
}
